### PR TITLE
Use precompiled CAPI from github release page

### PR DESCRIPTION
**Pull request by cschwan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scarlehoff** [comment]
You can check for `$HOST == *apple*` and then have a further conditional on `$HOST == *arm64-apple*` in case `gcc` is not found in x86.

**Comment by cschwan** [comment]
Does that mean you expect it to fail on `x86_64-apple-darwin`?

**Comment by scarlehoff** [comment]
When I was trying to write the Apple Silicon recipe I think osx_64 was also failing due to gcc being missing.

**Comment by cschwan** [comment]
Interestingly it only fails on Linux, where is the `$HOST` variable documented?

**Pull request merged**
